version: '3'
    
services:
        db:
            image: postgres
        web:
            build:
                context: .
                dockerfile: Dockerfile-back
            command: bundle update bootsnap
            command: bundle exec rails s -p 3000 -b '0.0.0.0'
            volumes:
                - .:/pokemon_api
            ports:
                - 3000:3000
            depends_on:
                - db
        front:
            build:
                context: .
                dockerfile: Dockerfile-front
            command: bash -c "npm install && npm start"
            ports:
                - 3001:3000
            depends_on:
                - web
            links:
                - web
            volumes:
                - ./front-end:/app
                - /app/node_modules
