development: &default
    adapter: postgresql
    econding: unicode
    database: pokemon_development
    pool: 5
    username: postgres
    password: 
    host: db

test:
    <<: *default
    database: pokemon_test

