# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Pokemon.create(indetifier: '1', name: 'bulbasaur', type1: 'poison', type2: 'grass')
Pokemon.create(indetifier: '2', name: 'ivysaur', type1: 'poison', type2: 'grass')
Pokemon.create(indetifier: '3', name: 'venusaur', type1: 'poison', type2: 'grass')
Pokemon.create(indetifier: '4', name: 'charmander', type1: 'fire', type2: 'None')
Pokemon.create(indetifier: '5', name: 'charmeleon', type1: 'fire', type2: 'None')
Pokemon.create(indetifier: '6', name: 'charizard', type1: 'flying', type2: 'fire')
Pokemon.create(indetifier: '7', name: 'squirtle', type1: 'water', type2: 'None')
Pokemon.create(indetifier: '8', name: 'wartortle', type1: 'water', type2: 'None')
Pokemon.create(indetifier: '9', name: 'blastoise', type1: 'water', type2: 'None')
Pokemon.create(indetifier: '10', name: 'caterpie', type1: 'bug', type2: 'None')
Pokemon.create(indetifier: '11', name: 'metapod', type1: 'bug', type2: 'None')
Pokemon.create(indetifier: '12', name: 'butterfree', type1: 'flying', type2: 'bug')
Pokemon.create(indetifier: '13', name: 'weedle', type1: 'poison', type2: 'bug')
Pokemon.create(indetifier: '14', name: 'kakuna', type1: 'poison', type2: 'bug')
Pokemon.create(indetifier: '15', name: 'beedrill', type1: 'poison', type2: 'bug')
Pokemon.create(indetifier: '16', name: 'pidgey', type1: 'flying', type2: 'normal')
Pokemon.create(indetifier: '17', name: 'pidgeotto', type1: 'flying', type2: 'normal')
Pokemon.create(indetifier: '18', name: 'pidgeot', type1: 'flying', type2: 'normal')
Pokemon.create(indetifier: '19', name: 'rattata', type1: 'normal', type2: 'None')
Pokemon.create(indetifier: '20', name: 'raticate', type1: 'normal', type2: 'None')
Pokemon.create(indetifier: '21', name: 'spearow', type1: 'flying', type2: 'normal')
Pokemon.create(indetifier: '22', name: 'fearow', type1: 'flying', type2: 'normal')
Pokemon.create(indetifier: '23', name: 'ekans', type1: 'poison', type2: 'None')
Pokemon.create(indetifier: '24', name: 'arbok', type1: 'poison', type2: 'None')
Pokemon.create(indetifier: '25', name: 'pikachu', type1: 'electric', type2: 'None')
Pokemon.create(indetifier: '26', name: 'raichu', type1: 'electric', type2: 'None')
Pokemon.create(indetifier: '27', name: 'sandshrew', type1: 'ground', type2: 'None')
Pokemon.create(indetifier: '28', name: 'sandslash', type1: 'ground', type2: 'None')
Pokemon.create(indetifier: '29', name: 'nidoran-f', type1: 'poison', type2: 'None')
Pokemon.create(indetifier: '30', name: 'nidorina', type1: 'poison', type2: 'None')
Pokemon.create(indetifier: '31', name: 'nidoqueen', type1: 'ground', type2: 'poison')
Pokemon.create(indetifier: '32', name: 'nidoran-m', type1: 'poison', type2: 'None')
Pokemon.create(indetifier: '33', name: 'nidorino', type1: 'poison', type2: 'None')
Pokemon.create(indetifier: '34', name: 'nidoking', type1: 'ground', type2: 'poison')
Pokemon.create(indetifier: '35', name: 'clefairy', type1: 'fairy', type2: 'None')
Pokemon.create(indetifier: '36', name: 'clefable', type1: 'fairy', type2: 'None')
Pokemon.create(indetifier: '37', name: 'vulpix', type1: 'fire', type2: 'None')
Pokemon.create(indetifier: '38', name: 'ninetales', type1: 'fire', type2: 'None')
Pokemon.create(indetifier: '39', name: 'jigglypuff', type1: 'fairy', type2: 'normal')
Pokemon.create(indetifier: '40', name: 'wigglytuff', type1: 'fairy', type2: 'normal')
Pokemon.create(indetifier: '41', name: 'zubat', type1: 'flying', type2: 'poison')
Pokemon.create(indetifier: '42', name: 'golbat', type1: 'flying', type2: 'poison')
Pokemon.create(indetifier: '43', name: 'oddish', type1: 'poison', type2: 'grass')
Pokemon.create(indetifier: '44', name: 'gloom', type1: 'poison', type2: 'grass')
Pokemon.create(indetifier: '45', name: 'vileplume', type1: 'poison', type2: 'grass')
Pokemon.create(indetifier: '46', name: 'paras', type1: 'grass', type2: 'bug')
Pokemon.create(indetifier: '47', name: 'parasect', type1: 'grass', type2: 'bug')
Pokemon.create(indetifier: '48', name: 'venonat', type1: 'poison', type2: 'bug')
Pokemon.create(indetifier: '49', name: 'venomoth', type1: 'poison', type2: 'bug')
Pokemon.create(indetifier: '50', name: 'diglett', type1: 'ground', type2: 'None')
Pokemon.create(indetifier: '51', name: 'dugtrio', type1: 'ground', type2: 'None')
Pokemon.create(indetifier: '52', name: 'meowth', type1: 'normal', type2: 'None')
Pokemon.create(indetifier: '53', name: 'persian', type1: 'normal', type2: 'None')
Pokemon.create(indetifier: '54', name: 'psyduck', type1: 'water', type2: 'None')
Pokemon.create(indetifier: '55', name: 'golduck', type1: 'water', type2: 'None')
Pokemon.create(indetifier: '56', name: 'mankey', type1: 'fighting', type2: 'None')
Pokemon.create(indetifier: '57', name: 'primeape', type1: 'fighting', type2: 'None')
Pokemon.create(indetifier: '58', name: 'growlithe', type1: 'fire', type2: 'None')
Pokemon.create(indetifier: '59', name: 'arcanine', type1: 'fire', type2: 'None')
Pokemon.create(indetifier: '60', name: 'poliwag', type1: 'water', type2: 'None')
Pokemon.create(indetifier: '61', name: 'poliwhirl', type1: 'water', type2: 'None')
Pokemon.create(indetifier: '62', name: 'poliwrath', type1: 'fighting', type2: 'water')
Pokemon.create(indetifier: '63', name: 'abra', type1: 'psychic', type2: 'None')
Pokemon.create(indetifier: '64', name: 'kadabra', type1: 'psychic', type2: 'None')
Pokemon.create(indetifier: '65', name: 'alakazam', type1: 'psychic', type2: 'None')
Pokemon.create(indetifier: '66', name: 'machop', type1: 'fighting', type2: 'None')
Pokemon.create(indetifier: '67', name: 'machoke', type1: 'fighting', type2: 'None')
Pokemon.create(indetifier: '68', name: 'machamp', type1: 'fighting', type2: 'None')
Pokemon.create(indetifier: '69', name: 'bellsprout', type1: 'poison', type2: 'grass')
Pokemon.create(indetifier: '70', name: 'weepinbell', type1: 'poison', type2: 'grass')
Pokemon.create(indetifier: '71', name: 'victreebel', type1: 'poison', type2: 'grass')
Pokemon.create(indetifier: '72', name: 'tentacool', type1: 'poison', type2: 'water')
Pokemon.create(indetifier: '73', name: 'tentacruel', type1: 'poison', type2: 'water')
Pokemon.create(indetifier: '74', name: 'geodude', type1: 'ground', type2: 'rock')
Pokemon.create(indetifier: '75', name: 'graveler', type1: 'ground', type2: 'rock')
Pokemon.create(indetifier: '76', name: 'golem', type1: 'ground', type2: 'rock')
Pokemon.create(indetifier: '77', name: 'ponyta', type1: 'fire', type2: 'None')
Pokemon.create(indetifier: '78', name: 'rapidash', type1: 'fire', type2: 'None')
Pokemon.create(indetifier: '79', name: 'slowpoke', type1: 'psychic', type2: 'water')
Pokemon.create(indetifier: '80', name: 'slowbro', type1: 'psychic', type2: 'water')
Pokemon.create(indetifier: '81', name: 'magnemite', type1: 'steel', type2: 'electric')
Pokemon.create(indetifier: '82', name: 'magneton', type1: 'steel', type2: 'electric')
Pokemon.create(indetifier: '83', name: 'farfetchd', type1: 'flying', type2: 'normal')
Pokemon.create(indetifier: '84', name: 'doduo', type1: 'flying', type2: 'normal')
Pokemon.create(indetifier: '85', name: 'dodrio', type1: 'flying', type2: 'normal')
Pokemon.create(indetifier: '86', name: 'seel', type1: 'water', type2: 'None')
Pokemon.create(indetifier: '87', name: 'dewgong', type1: 'ice', type2: 'water')
Pokemon.create(indetifier: '88', name: 'grimer', type1: 'poison', type2: 'None')
Pokemon.create(indetifier: '89', name: 'muk', type1: 'poison', type2: 'None')
Pokemon.create(indetifier: '90', name: 'shellder', type1: 'water', type2: 'None')
Pokemon.create(indetifier: '91', name: 'cloyster', type1: 'ice', type2: 'water')
Pokemon.create(indetifier: '92', name: 'gastly', type1: 'poison', type2: 'ghost')
Pokemon.create(indetifier: '93', name: 'haunter', type1: 'poison', type2: 'ghost')
Pokemon.create(indetifier: '94', name: 'gengar', type1: 'poison', type2: 'ghost')
Pokemon.create(indetifier: '95', name: 'onix', type1: 'ground', type2: 'rock')
Pokemon.create(indetifier: '96', name: 'drowzee', type1: 'psychic', type2: 'None')
Pokemon.create(indetifier: '97', name: 'hypno', type1: 'psychic', type2: 'None')
Pokemon.create(indetifier: '98', name: 'krabby', type1: 'water', type2: 'None')
Pokemon.create(indetifier: '99', name: 'kingler', type1: 'water', type2: 'None')
Pokemon.create(indetifier: '100', name: 'voltorb', type1: 'electric', type2: 'None')
Pokemon.create(indetifier: '101', name: 'electrode', type1: 'electric', type2: 'None')
Pokemon.create(indetifier: '102', name: 'exeggcute', type1: 'psychic', type2: 'grass')
Pokemon.create(indetifier: '103', name: 'exeggutor', type1: 'psychic', type2: 'grass')
Pokemon.create(indetifier: '104', name: 'cubone', type1: 'ground', type2: 'None')
Pokemon.create(indetifier: '105', name: 'marowak', type1: 'ground', type2: 'None')
Pokemon.create(indetifier: '106', name: 'hitmonlee', type1: 'fighting', type2: 'None')
Pokemon.create(indetifier: '107', name: 'hitmonchan', type1: 'fighting', type2: 'None')
Pokemon.create(indetifier: '108', name: 'lickitung', type1: 'normal', type2: 'None')
Pokemon.create(indetifier: '109', name: 'koffing', type1: 'poison', type2: 'None')
Pokemon.create(indetifier: '110', name: 'weezing', type1: 'poison', type2: 'None')
Pokemon.create(indetifier: '111', name: 'rhyhorn', type1: 'rock', type2: 'ground')
Pokemon.create(indetifier: '112', name: 'rhydon', type1: 'rock', type2: 'ground')
Pokemon.create(indetifier: '113', name: 'chansey', type1: 'normal', type2: 'None')
Pokemon.create(indetifier: '114', name: 'tangela', type1: 'grass', type2: 'None')
Pokemon.create(indetifier: '115', name: 'kangaskhan', type1: 'normal', type2: 'None')
Pokemon.create(indetifier: '116', name: 'horsea', type1: 'water', type2: 'None')
Pokemon.create(indetifier: '117', name: 'seadra', type1: 'water', type2: 'None')
Pokemon.create(indetifier: '118', name: 'goldeen', type1: 'water', type2: 'None')
Pokemon.create(indetifier: '119', name: 'seaking', type1: 'water', type2: 'None')
Pokemon.create(indetifier: '120', name: 'staryu', type1: 'water', type2: 'None')
Pokemon.create(indetifier: '121', name: 'starmie', type1: 'psychic', type2: 'water')
Pokemon.create(indetifier: '122', name: 'mr-mime', type1: 'fairy', type2: 'psychic')
Pokemon.create(indetifier: '123', name: 'scyther', type1: 'flying', type2: 'bug')
Pokemon.create(indetifier: '124', name: 'jynx', type1: 'psychic', type2: 'ice')
Pokemon.create(indetifier: '125', name: 'electabuzz', type1: 'electric', type2: 'None')
Pokemon.create(indetifier: '126', name: 'magmar', type1: 'fire', type2: 'None')
Pokemon.create(indetifier: '127', name: 'pinsir', type1: 'bug', type2: 'None')
Pokemon.create(indetifier: '128', name: 'tauros', type1: 'normal', type2: 'None')
Pokemon.create(indetifier: '129', name: 'magikarp', type1: 'water', type2: 'None')
Pokemon.create(indetifier: '130', name: 'gyarados', type1: 'flying', type2: 'water')
Pokemon.create(indetifier: '131', name: 'lapras', type1: 'ice', type2: 'water')
Pokemon.create(indetifier: '132', name: 'ditto', type1: 'normal', type2: 'None')
Pokemon.create(indetifier: '133', name: 'eevee', type1: 'normal', type2: 'None')
Pokemon.create(indetifier: '134', name: 'vaporeon', type1: 'water', type2: 'None')
Pokemon.create(indetifier: '135', name: 'jolteon', type1: 'electric', type2: 'None')
Pokemon.create(indetifier: '136', name: 'flareon', type1: 'fire', type2: 'None')
Pokemon.create(indetifier: '137', name: 'porygon', type1: 'normal', type2: 'None')
Pokemon.create(indetifier: '138', name: 'omanyte', type1: 'water', type2: 'rock')
Pokemon.create(indetifier: '139', name: 'omastar', type1: 'water', type2: 'rock')
Pokemon.create(indetifier: '140', name: 'kabuto', type1: 'water', type2: 'rock')
Pokemon.create(indetifier: '141', name: 'kabutops', type1: 'water', type2: 'rock')
Pokemon.create(indetifier: '142', name: 'aerodactyl', type1: 'flying', type2: 'rock')
Pokemon.create(indetifier: '143', name: 'snorlax', type1: 'normal', type2: 'None')
Pokemon.create(indetifier: '144', name: 'articuno', type1: 'flying', type2: 'ice')
Pokemon.create(indetifier: '145', name: 'zapdos', type1: 'flying', type2: 'electric')
Pokemon.create(indetifier: '146', name: 'moltres', type1: 'flying', type2: 'fire')
Pokemon.create(indetifier: '147', name: 'dratini', type1: 'dragon', type2: 'None')
Pokemon.create(indetifier: '148', name: 'dragonair', type1: 'dragon', type2: 'None')
Pokemon.create(indetifier: '149', name: 'dragonite', type1: 'flying', type2: 'dragon')
Pokemon.create(indetifier: '150', name: 'mewtwo', type1: 'psychic', type2: 'None')
Pokemon.create(indetifier: '151', name: 'mew', type1: 'psychic', type2: 'None')


Evolution.create(pokemon:'bulbasaur',first_evolution:'ivysaur',second_evolution:'venusaur')
Evolution.create(pokemon:'ivysaur',first_evolution:'venusaur',second_evolution:'bulbasaur')
Evolution.create(pokemon:'venusaur',first_evolution:'bulbasaur',second_evolution:'ivysaur')
Evolution.create(pokemon:'charmander',first_evolution:'charmeleon',second_evolution:'charizard')
Evolution.create(pokemon:'charmeleon',first_evolution:'charizard',second_evolution:'charmander')
Evolution.create(pokemon:'charizard',first_evolution:'charmander',second_evolution:'charmeleon')
Evolution.create(pokemon:'squirtle',first_evolution:'wartortle',second_evolution:'blastoise')
Evolution.create(pokemon:'wartortle',first_evolution:'blastoise',second_evolution:'squirtle')
Evolution.create(pokemon:'blastoise',first_evolution:'squirtle',second_evolution:'wartortle')
Evolution.create(pokemon:'caterpie',first_evolution:'metapod',second_evolution:'butterfree')
Evolution.create(pokemon:'metapod',first_evolution:'butterfree',second_evolution:'caterpie')
Evolution.create(pokemon:'butterfree',first_evolution:'caterpie',second_evolution:'metapod')
Evolution.create(pokemon:'weedle',first_evolution:'kakuna',second_evolution:'beedrill')
Evolution.create(pokemon:'kakuna',first_evolution:'beedrill',second_evolution:'weedle')
Evolution.create(pokemon:'beedrill',first_evolution:'weedle',second_evolution:'kakuna')
Evolution.create(pokemon:'pidgey',first_evolution:'pidgeotto',second_evolution:'pidgeot')
Evolution.create(pokemon:'pidgeotto',first_evolution:'pidgeot',second_evolution:'pidgey')
Evolution.create(pokemon:'pidgeot',first_evolution:'pidgey',second_evolution:'pidgeotto')
Evolution.create(pokemon:'rattata',first_evolution:'raticate',second_evolution:'None')
Evolution.create(pokemon:'raticate',first_evolution:'None',second_evolution:'rattata')
Evolution.create(pokemon:'spearow',first_evolution:'fearow',second_evolution:'None')
Evolution.create(pokemon:'fearow',first_evolution:'None',second_evolution:'spearow')
Evolution.create(pokemon:'ekans',first_evolution:'arbok',second_evolution:'None')
Evolution.create(pokemon:'arbok',first_evolution:'None',second_evolution:'ekans')
Evolution.create(pokemon:'pichu',first_evolution:'pikachu',second_evolution:'raichu')
Evolution.create(pokemon:'pikachu',first_evolution:'raichu',second_evolution:'pichu')
Evolution.create(pokemon:'raichu',first_evolution:'pichu',second_evolution:'pikachu')
Evolution.create(pokemon:'sandshrew',first_evolution:'sandslash',second_evolution:'None')
Evolution.create(pokemon:'sandslash',first_evolution:'None',second_evolution:'sandshrew')
Evolution.create(pokemon:'nidoran-f',first_evolution:'nidorina',second_evolution:'nidoqueen')
Evolution.create(pokemon:'nidorina',first_evolution:'nidoqueen',second_evolution:'nidoran-f')
Evolution.create(pokemon:'nidoqueen',first_evolution:'nidoran-f',second_evolution:'nidorina')
Evolution.create(pokemon:'nidoran-m',first_evolution:'nidorino',second_evolution:'nidoking')
Evolution.create(pokemon:'nidorino',first_evolution:'nidoking',second_evolution:'nidoran-m')
Evolution.create(pokemon:'nidoking',first_evolution:'nidoran-m',second_evolution:'nidorino')
Evolution.create(pokemon:'cleffa',first_evolution:'clefairy',second_evolution:'clefable')
Evolution.create(pokemon:'clefairy',first_evolution:'clefable',second_evolution:'cleffa')
Evolution.create(pokemon:'clefable',first_evolution:'cleffa',second_evolution:'clefairy')
Evolution.create(pokemon:'vulpix',first_evolution:'ninetales',second_evolution:'None')
Evolution.create(pokemon:'ninetales',first_evolution:'None',second_evolution:'vulpix')
Evolution.create(pokemon:'igglybuff',first_evolution:'jigglypuff',second_evolution:'wigglytuff')
Evolution.create(pokemon:'jigglypuff',first_evolution:'wigglytuff',second_evolution:'igglybuff')
Evolution.create(pokemon:'wigglytuff',first_evolution:'igglybuff',second_evolution:'jigglypuff')
Evolution.create(pokemon:'zubat',first_evolution:'golbat',second_evolution:'crobat')
Evolution.create(pokemon:'golbat',first_evolution:'crobat',second_evolution:'zubat')
Evolution.create(pokemon:'crobat',first_evolution:'zubat',second_evolution:'golbat')
Evolution.create(pokemon:'oddish',first_evolution:'gloom',second_evolution:'vileplume')
Evolution.create(pokemon:'gloom',first_evolution:'vileplume',second_evolution:'oddish')
Evolution.create(pokemon:'vileplume',first_evolution:'oddish',second_evolution:'gloom')
Evolution.create(pokemon:'paras',first_evolution:'parasect',second_evolution:'None')
Evolution.create(pokemon:'parasect',first_evolution:'None',second_evolution:'paras')
Evolution.create(pokemon:'venonat',first_evolution:'venomoth',second_evolution:'None')
Evolution.create(pokemon:'venomoth',first_evolution:'None',second_evolution:'venonat')
Evolution.create(pokemon:'diglett',first_evolution:'dugtrio',second_evolution:'None')
Evolution.create(pokemon:'dugtrio',first_evolution:'None',second_evolution:'diglett')
Evolution.create(pokemon:'meowth',first_evolution:'persian',second_evolution:'None')
Evolution.create(pokemon:'persian',first_evolution:'None',second_evolution:'meowth')
Evolution.create(pokemon:'psyduck',first_evolution:'golduck',second_evolution:'None')
Evolution.create(pokemon:'golduck',first_evolution:'None',second_evolution:'psyduck')
Evolution.create(pokemon:'mankey',first_evolution:'primeape',second_evolution:'None')
Evolution.create(pokemon:'primeape',first_evolution:'None',second_evolution:'mankey')
Evolution.create(pokemon:'growlithe',first_evolution:'arcanine',second_evolution:'None')
Evolution.create(pokemon:'arcanine',first_evolution:'None',second_evolution:'growlithe')
Evolution.create(pokemon:'poliwag',first_evolution:'poliwhirl',second_evolution:'poliwrath')
Evolution.create(pokemon:'poliwhirl',first_evolution:'poliwrath',second_evolution:'poliwag')
Evolution.create(pokemon:'poliwrath',first_evolution:'poliwag',second_evolution:'poliwhirl')
Evolution.create(pokemon:'abra',first_evolution:'kadabra',second_evolution:'alakazam')
Evolution.create(pokemon:'kadabra',first_evolution:'alakazam',second_evolution:'abra')
Evolution.create(pokemon:'alakazam',first_evolution:'abra',second_evolution:'kadabra')
Evolution.create(pokemon:'machop',first_evolution:'machoke',second_evolution:'machamp')
Evolution.create(pokemon:'machoke',first_evolution:'machamp',second_evolution:'machop')
Evolution.create(pokemon:'machamp',first_evolution:'machop',second_evolution:'machoke')
Evolution.create(pokemon:'bellsprout',first_evolution:'weepinbell',second_evolution:'victreebel')
Evolution.create(pokemon:'weepinbell',first_evolution:'victreebel',second_evolution:'bellsprout')
Evolution.create(pokemon:'victreebel',first_evolution:'bellsprout',second_evolution:'weepinbell')
Evolution.create(pokemon:'tentacool',first_evolution:'tentacruel',second_evolution:'None')
Evolution.create(pokemon:'tentacruel',first_evolution:'None',second_evolution:'tentacool')
Evolution.create(pokemon:'geodude',first_evolution:'graveler',second_evolution:'golem')
Evolution.create(pokemon:'graveler',first_evolution:'golem',second_evolution:'geodude')
Evolution.create(pokemon:'golem',first_evolution:'geodude',second_evolution:'graveler')
Evolution.create(pokemon:'ponyta',first_evolution:'rapidash',second_evolution:'None')
Evolution.create(pokemon:'rapidash',first_evolution:'None',second_evolution:'ponyta')
Evolution.create(pokemon:'slowpoke',first_evolution:'slowking',second_evolution:'None')
Evolution.create(pokemon:'slowking',first_evolution:'None',second_evolution:'slowpoke')
Evolution.create(pokemon:'magnemite',first_evolution:'magneton',second_evolution:'magnezone')
Evolution.create(pokemon:'magneton',first_evolution:'magnezone',second_evolution:'magnemite')
Evolution.create(pokemon:'magnezone',first_evolution:'magnemite',second_evolution:'magneton')
Evolution.create(pokemon:'farfetchd',first_evolution:'None',second_evolution:'None')
Evolution.create(pokemon:'doduo',first_evolution:'dodrio',second_evolution:'None')
Evolution.create(pokemon:'dodrio',first_evolution:'None',second_evolution:'doduo')
Evolution.create(pokemon:'seel',first_evolution:'dewgong',second_evolution:'None')
Evolution.create(pokemon:'dewgong',first_evolution:'None',second_evolution:'seel')
Evolution.create(pokemon:'grimer',first_evolution:'muk',second_evolution:'None')
Evolution.create(pokemon:'muk',first_evolution:'None',second_evolution:'grimer')
Evolution.create(pokemon:'shellder',first_evolution:'cloyster',second_evolution:'None')
Evolution.create(pokemon:'cloyster',first_evolution:'None',second_evolution:'shellder')
Evolution.create(pokemon:'gastly',first_evolution:'haunter',second_evolution:'gengar')
Evolution.create(pokemon:'haunter',first_evolution:'gengar',second_evolution:'gastly')
Evolution.create(pokemon:'gengar',first_evolution:'gastly',second_evolution:'haunter')
Evolution.create(pokemon:'onix',first_evolution:'steelix',second_evolution:'None')
Evolution.create(pokemon:'steelix',first_evolution:'None',second_evolution:'onix')
Evolution.create(pokemon:'drowzee',first_evolution:'hypno',second_evolution:'None')
Evolution.create(pokemon:'hypno',first_evolution:'None',second_evolution:'drowzee')
Evolution.create(pokemon:'krabby',first_evolution:'kingler',second_evolution:'None')
Evolution.create(pokemon:'kingler',first_evolution:'None',second_evolution:'krabby')
Evolution.create(pokemon:'voltorb',first_evolution:'electrode',second_evolution:'None')
Evolution.create(pokemon:'electrode',first_evolution:'None',second_evolution:'voltorb')
Evolution.create(pokemon:'exeggcute',first_evolution:'exeggutor',second_evolution:'None')
Evolution.create(pokemon:'exeggutor',first_evolution:'None',second_evolution:'exeggcute')
Evolution.create(pokemon:'cubone',first_evolution:'marowak',second_evolution:'None')
Evolution.create(pokemon:'marowak',first_evolution:'None',second_evolution:'cubone')
Evolution.create(pokemon:'tyrogue',first_evolution:'hitmontop',second_evolution:'None')
Evolution.create(pokemon:'hitmontop',first_evolution:'None',second_evolution:'tyrogue')
Evolution.create(pokemon:'lickitung',first_evolution:'lickilicky',second_evolution:'None')
Evolution.create(pokemon:'lickilicky',first_evolution:'None',second_evolution:'lickitung')
Evolution.create(pokemon:'koffing',first_evolution:'weezing',second_evolution:'None')
Evolution.create(pokemon:'weezing',first_evolution:'None',second_evolution:'koffing')
Evolution.create(pokemon:'rhyhorn',first_evolution:'rhydon',second_evolution:'rhyperior')
Evolution.create(pokemon:'rhydon',first_evolution:'rhyperior',second_evolution:'rhyhorn')
Evolution.create(pokemon:'rhyperior',first_evolution:'rhyhorn',second_evolution:'rhydon')
Evolution.create(pokemon:'happiny',first_evolution:'chansey',second_evolution:'blissey')
Evolution.create(pokemon:'chansey',first_evolution:'blissey',second_evolution:'happiny')
Evolution.create(pokemon:'blissey',first_evolution:'happiny',second_evolution:'chansey')
Evolution.create(pokemon:'tangela',first_evolution:'tangrowth',second_evolution:'None')
Evolution.create(pokemon:'tangrowth',first_evolution:'None',second_evolution:'tangela')
Evolution.create(pokemon:'kangaskhan',first_evolution:'None',second_evolution:'None')
Evolution.create(pokemon:'horsea',first_evolution:'seadra',second_evolution:'kingdra')
Evolution.create(pokemon:'seadra',first_evolution:'kingdra',second_evolution:'horsea')
Evolution.create(pokemon:'kingdra',first_evolution:'horsea',second_evolution:'seadra')
Evolution.create(pokemon:'goldeen',first_evolution:'seaking',second_evolution:'None')
Evolution.create(pokemon:'seaking',first_evolution:'None',second_evolution:'goldeen')
Evolution.create(pokemon:'staryu',first_evolution:'starmie',second_evolution:'None')
Evolution.create(pokemon:'starmie',first_evolution:'None',second_evolution:'staryu')
Evolution.create(pokemon:'mime-jr',first_evolution:'mr-mime',second_evolution:'None')
Evolution.create(pokemon:'mr-mime',first_evolution:'None',second_evolution:'mime-jr')
Evolution.create(pokemon:'scyther',first_evolution:'scizor',second_evolution:'None')
Evolution.create(pokemon:'scizor',first_evolution:'None',second_evolution:'scyther')
Evolution.create(pokemon:'smoochum',first_evolution:'jynx',second_evolution:'None')
Evolution.create(pokemon:'jynx',first_evolution:'None',second_evolution:'smoochum')
Evolution.create(pokemon:'elekid',first_evolution:'electabuzz',second_evolution:'electivire')
Evolution.create(pokemon:'electabuzz',first_evolution:'electivire',second_evolution:'elekid')
Evolution.create(pokemon:'electivire',first_evolution:'elekid',second_evolution:'electabuzz')
Evolution.create(pokemon:'magby',first_evolution:'magmar',second_evolution:'magmortar')
Evolution.create(pokemon:'magmar',first_evolution:'magmortar',second_evolution:'magby')
Evolution.create(pokemon:'magmortar',first_evolution:'magby',second_evolution:'magmar')
Evolution.create(pokemon:'pinsir',first_evolution:'None',second_evolution:'None')
Evolution.create(pokemon:'tauros',first_evolution:'None',second_evolution:'None')
Evolution.create(pokemon:'magikarp',first_evolution:'gyarados',second_evolution:'None')
Evolution.create(pokemon:'gyarados',first_evolution:'None',second_evolution:'magikarp')
Evolution.create(pokemon:'lapras',first_evolution:'None',second_evolution:'None')
Evolution.create(pokemon:'ditto',first_evolution:'None',second_evolution:'None')
Evolution.create(pokemon:'eevee',first_evolution:'sylveon',second_evolution:'None')
Evolution.create(pokemon:'sylveon',first_evolution:'None',second_evolution:'eevee')
Evolution.create(pokemon:'porygon',first_evolution:'porygon2',second_evolution:'porygon-z')
Evolution.create(pokemon:'porygon2',first_evolution:'porygon-z',second_evolution:'porygon')
Evolution.create(pokemon:'porygon-z',first_evolution:'porygon',second_evolution:'porygon2')
Evolution.create(pokemon:'omanyte',first_evolution:'omastar',second_evolution:'None')
Evolution.create(pokemon:'omastar',first_evolution:'None',second_evolution:'omanyte')
Evolution.create(pokemon:'kabuto',first_evolution:'kabutops',second_evolution:'None')
Evolution.create(pokemon:'kabutops',first_evolution:'None',second_evolution:'kabuto')
Evolution.create(pokemon:'aerodactyl',first_evolution:'None',second_evolution:'None')
Evolution.create(pokemon:'munchlax',first_evolution:'snorlax',second_evolution:'None')
Evolution.create(pokemon:'snorlax',first_evolution:'None',second_evolution:'munchlax')
Evolution.create(pokemon:'articuno',first_evolution:'None',second_evolution:'None')
Evolution.create(pokemon:'zapdos',first_evolution:'None',second_evolution:'None')
Evolution.create(pokemon:'moltres',first_evolution:'None',second_evolution:'None')
Evolution.create(pokemon:'dratini',first_evolution:'dragonair',second_evolution:'dragonite')
Evolution.create(pokemon:'dragonair',first_evolution:'dragonite',second_evolution:'dratini')
Evolution.create(pokemon:'dragonite',first_evolution:'dratini',second_evolution:'dragonair')
Evolution.create(pokemon:'mewtwo',first_evolution:'None',second_evolution:'None')
Evolution.create(pokemon:'mew',first_evolution:'None',second_evolution:'None')
